# Generated by Django 4.2.11 on 2024-03-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='event_type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District')], default='cultural', max_length=20),
        ),
    ]
