# Generated by Django 4.2.11 on 2024-03-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_student_is_active_alter_student_event_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_cultural',
        ),
    ]
