# Generated by Django 4.2.11 on 2024-03-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_student_sports_student_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_cultural',
            name='event_description',
            field=models.TextField(default='This is a cultural event.'),
        ),
        migrations.AddField(
            model_name='student_cultural',
            name='event_name',
            field=models.CharField(default='Cultural Event', max_length=100),
        ),
        migrations.AddField(
            model_name='student_sports',
            name='event_description',
            field=models.TextField(default='This is a sports event.'),
        ),
        migrations.AddField(
            model_name='student_sports',
            name='event_name',
            field=models.CharField(default='Sports Event', max_length=100),
        ),
        migrations.AddField(
            model_name='student_technical',
            name='event_description',
            field=models.TextField(default='This is a technical event.'),
        ),
        migrations.AddField(
            model_name='student_technical',
            name='event_name',
            field=models.CharField(default='Technical Event', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_cultural',
            name='name',
            field=models.CharField(default='Cultural Event', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_cultural',
            name='rollno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='name',
            field=models.CharField(default='Sports Event', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='rollno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='name',
            field=models.CharField(default='Technical Event', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='rollno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
