# Generated by Django 4.2.11 on 2025-04-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_student_cultural_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_cultural',
            name='event_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student_cultural',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_cultural',
            name='event_type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_cultural',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='event_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='event_type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='event_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='event_type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
